---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
spec:
  encryptedData:
    apikey: AgAh0AO5L22QMyempEd+g+71uHKKvX2re2tQsn8nZFJJsaq2Ik+zdj117xqT/l15yImx56/FBE8BadJBk7pKlVZ+Ow4OTsy62D2HR2i3wviQmAuW/4hWBU7ccgvChdaJApATt9yiMckPcaLoVwyXIzuxJOZ4mkR093hWpDAekm7/0qtfkYCUlQkL6oycieXtp1boXJPa9CZkc575NgKCDykpt01eI3ZNS2lgvJxPIARdFzMqbfrQt6oyjcZt713GSX4Dxa3oC3+uHEHA+lxhmkSUqhkfHkT6jVhoad8I8WXTLoGlBSeF9EZsakJ9kFcjxK77D8el3xB+1sZf5UHTdv7UkZtLoPB4z1HVrrB3u+9HeDpyhp79p8QqnfPhcpoZMxGk8GJkdRfSpHHiJfg8E+pmSGpDFmHJ2TxFy4d6+bqdw0V+KRUZeLPBVXyPf0F+bkIH9K5C9JP+D0tNI/8sYHUWZtC/GvnzKqibOYjkFjvHvXVLGDGK4S4Fn8R4wwAY5YVkMOKPaD+DhG90j+yMKLI0uXBpdnI06wSkJlv8PiDfIhT2dfBVnwKUPeJk1WP/F8xUgXTXOiRumk67OKsvLAvR/J4FVZjZw3lJiSsGb7+/3bP71nvPOf0bJyA13bsdyjFST20a1dAo0Ip+9JWQOsKPm6V1dbCx48g+ijxM/kg0isCL6RzAsQNY52h82tuRk29GWYTJXIU+qOlncZnKpv043dmr3wJzwL/0muq9qJJW3HgnSixWCNw=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
