---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
spec:
  encryptedData:
    apikey: AgAWvWZZ8MVkAAO0bfTuUziMJr0PS3HjW+vjL/YsZ+fAhyUJ96enGMa+gkfateR1oSadz0u7uwtLgZSOiUIvyxhTWnUmp9WBm0H7au6mlfV3Qm+Q8JaEc6EWf4lwOms0XY6ONFXDeeaG9a2Fmzli8Bms8L0qzOZkmSIUtvjItFEqgFy42gEqOWOOBBkKLuydhd+/v0BwLH3R0h+s7hKGrMr7bOmYG72SlUExuU34YzdxlTvrwMhohrNCd8eqAV8Mi7KaD3T0bH+3JwfzhK63T4Mvr6Z3Og4QA1Av25YV5qJUsxXJrBr/KxUXmPuGv5g4Pt2R9CO4lpSl5Nb5x0zlFjLlRYnbyRieEM5PXEN2jlknMpWACBsAtPnvxAjwpg5Qe6Nj2GPJmIz4LDjgJyG/tUOt1isKX7zET1baKYXUfNE4ga5Q3IWNGJQmAjhfiEARMdfN+i2s3b+UCRQkxGtaPaGOJL7Nyk1RalViXLxOEdV/8AFfPvzbsJodXrLALPqN71pCwEYVY/rti6qnXOJdJfQ71GKy+f692oE8hvoYoMov5/HJ38B5WqmO36+FiQJT4dUSo0eP8ox8A2HtnrI1tu/a8YnU/lBdsp2qZbfslXF22yxILiih1Ufk7XQliMqxeJZ6lOXdqsuXT9Jm7p0mNvWleJaua5KooUenDD1bJSx5Y8CBJ4aCqhxHOObTWYB+7cJD182Yieha1Vn+i0LhMLrszayH6nY7UqFIalceP4R64RqI0FaJl0A=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
