# Deployment Configuration

#annotations:
#  reloader.stakater.com/auto: "true" # Annotation for the Stakater Reloader, which automatically restarts the pod if ConfigMaps or Secrets change.

replicas: 2 # Defines the number of replicas for the deployment. In this case, two pods will be deployed.

#securityContextEnabled: true # Add securityContext flag
#securityContext: # Add default values for the securityContext
#   runAsUser: 65534  # nobody user
#   runAsGroup: 65534  # nogroup group

image:
  repository: nginx # Specifies the Docker image repository from an Azure Container Registry.
  tag: latest

container:
  name: nginx # Name of the container in the pod.
  port: 80 # Port on which the container will listen for incoming requests.

resources:
  limits:
    cpu: "500m"     # Maximum CPU allocation for the container (500 milliCPU).
    memory: "256Mi" # Maximum memory allocation for the container (256 MiB).
  requests:
    cpu: "200m"     # Minimum CPU allocation requested for the container (200 milliCPU).
    memory: "128Mi" # Minimum memory allocation requested for the container (128 MiB).



#
# ConfigMap Data
configMap:
  data:
    ASPNETCORE_ENVIRONMENT: "Development" # Environment variable for the .NET application, indicating the environment is "Development".
    


# Secret Data
secrets:
  data:
    AuditLogDbConnectionString: AgCtwEaHvZ8lAMYSwCP7rmwgb0f+sN+Jw9kgxfxPqBsGZiD3wRzMHgNsuC6OX7QqFS0sgtygoxfUoWXzB8DsEjgDo7ZN5/1xZKbxo5W6lRqUKi8Km18SZWkgOWE7bQ2gZeeCrB2bE/JpHXvFdgbu6u8191jBxR77N7Z9Zrsp4G2ROWarDtOw04QocX31XYUG7Rr9FaJtrzoSMJEmiWUk++mErNBBZ69GzET1RSAMs5aWJtA1iX66sEwzDLfy2lkSjAFMpLmUxmlcIDIr8iQ7LcV6EvdDIoiwRtpB00hcYKMy6pCm7vu/J3gqQAiCjaDkrLsWykxlayaTACNCGSWBwp/qD28sG29G+oYVm55BFxxFsvhHNESxj3DGsp90SwWMCn0Nn4D6RmDTMPDos9NqO7/XMUPGSxjRfXKc3lA7x+9/qv59S+da++Z/tiQm09zwcXbP0w0yAhkyBJi4bvi0pbmyFRfeCvccDLMkElJkpBYOPwR+8sposmzwYCw+Dg083w6QPxb9gtxwMa9C0CbMx3pjPH9Jq2XBNSvFVVDlWOmInBACYiF7Ct8rXuTOMN4tvsqWgikPr0Vf6hgLZ2Tg3nk/kjNKEsJMPl5hGPNwSUnOJt5xJsSpb5bzzcxsVFbD956bea79eCDH890bCaV1/I0TDG7WK4uF0KwjJ0Jc6JtpCxfJ22NJG1yzyDulWRFnYpYXbQC/JwGNgQqCj37dfu3RU1s3xex9+zvcTeKqbwD92ocUhABs4sT7TJk7tEyH5MsG+kcNNNVsTk52zF1eDBF7ht1fHKpoB97Exw4cy7O8cjzdJVAxe+2y4TLrlUcBgh9wp8E66Ey/mbOsh3mSRd40gDyQkmQkUxPnHvIJzZ4Tl3nsWft3qBQpnC/DXWbu0ovU/S7V4JJevNlOM6qS79JBT3dhDfaYeH7iIyM24Q==
    CordysUsername: AgAW5FJftby6FxhSF3KePwRxKLrkDCDlMA2D6vykR5G/rDG1HYbVOipbtgWOk3WTFitnNtR0oIbyc/9xe6uf5rOJsP3Vv10yuhUQwKjcqD7vX4nDY87DTtXMW/59eBoNOu9rfcqgTCbjT/TVkpC9ZUdeI6xh029mRtY3fhY9X9hJVGPqc1b/dqwxVU7dGSQ/KRirEfwhd6jLND/8WrQSBjObtn5hDYE76rnAxzYNo11VJ0Ih5ImifbhZUoY7jLTCR7hck+HBwyprptJYMWVuh2YMfC+OmAPYhHxlGPH0RQIgUrHhebcmeYEhLc2y2wtm/Qwr+AjGgx0RnO5i+VQ980Z30RbsamJcWhz+HYvfJ1FGBbEj9NegdsZQVOulu/+q3eKOe9Tb2oUQMCVOH1WWq7QYw7AsSFSheXn/x/j677ywIIbBarxfPu5iyA45HM2w3/Uf6byA3y423ib6nQY/SBFIMLiupWCgM+4t868syUJ/TqqMgCoednk76TM+IyPQyKY8CdQ+E5le7exn/uY4fJf4nOjhpza8JpRbMGBHpAuwW2D+2PoItSuAdv1eg8IAKnIG0fV8TpUAs8lVswA126L5D19VEbl2m4D1V+fkFTjrTHGxVGN3opjIAl8RF7j8tpJ5ZU1RxyWIyYS4IAJ+s3ru2heqlZSDgBIY1w9aA9/9wbZp8A5u9e23jYp74BJBB7FjvmW1etVOSEP29jP+gg==
    OracleDbConnectionString: AgCtauKWtwoD72opZQEKEl6IAfHnHhWJlhaF55Uu4ixKxSk5i2861teGQWvp8VK9qFYUc+UXr9knoe0pFKzMndRJQisDPx7r2Nz84SnEFPo5+BPt8sPjDA66kGJbWtzU5Rbz2ElSQongh3m5kS5yKH4cs4WPnpGCBqygJIT/cFD+luy/NdHH0bI8UM7RNfF5OIre0espKIulTm08tRn951CXRXBTKXI89unHEovDSN5ovkzhJ4sUD+u3OzO7zWtIH7OIioZreXvRli1jdZZKyOV5W/ZV/7hnXwhh6NMEbyQA7tzxOWQPht6YAsVWp0eX47QsaGqyGvw3C1xeJ5Usq42Z13TiUVcS57R6Dr+p9VC8+ZnCYbSgWxLHqgsdlaIUDWoSpJ+zE1aEUsFR0qQNE86ISkILZWnX+URdmaVlzftshSTF6O4ndzwPmVhIzBLtEZAT+iVX9TotnOhq8T8Ihj5cd6QF0bte3uwuXezq8rZNpgCCauEpmHacXdZpkS8qGjD7dnM7/dVmONEeUZ0zPvhcsbBw5Bs8jxlLj1Kg+wQm3Gm+mO7tSo3V+9eBoVdPqSN1dY8kaB0NZ2MGpUWilegHCMYHtRWgPBtWndoSbtF+G90jeYXEfRL5pH2rwm4qxQmfVZiSU9Xc39E4RontbO7GXbyyTwmz3EWf0G/uTknx/aNclidJzlg0+W7qaVj5jAa4fsQqEQFXKThZKXX8ev1rvGhG5DQb1NQ/UN8PIeb24le1JcM2lUGNRlStsYFmNuSaOITjKjDN2i5bgcZvLOQSrkZ1eXGH+GIe04izCzdZ3EZT62TGxNwoHTeE5BEK2vNo0zSRKHhbTQD21GbT02BQn5a5dGk3eL+XBtrFD1GP/E4+oW+rM8/Rx8WRAOxI5+Xow8nyCkUixJ/t4qAGqYW9JJF6HWAgXO5J0jjLwCh/sptgI92q0ij59gcCYA==
# Service Configuration
service:
  type: ClusterIP  # Defines the type of Kubernetes service. ClusterIP exposes the service internally within the cluster.
  port: 80         # Port that the service will expose externally (within the cluster in this case).
  targetPort: 80 # The port on the container to which the service will route traffic.

# Ingress Configuration
ingress:
  enabled: false # Enables the creation of an Ingress resource to manage external access to the service.
  className: "nginx"  # Specifies the Ingress class for the controller, in this case NGINX (e.g., it could be Traefik or another controller).

  # Ingress annotations (can be used to configure specific ingress controller features)
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"  # Example annotation for NGINX Ingress to rewrite URLs. Uncomment if needed.

  hosts:
    - host:   # The hostname for accessing the application via Ingress.
      paths:
        - path: /nginx(/|$)(.*)       # The root path for the frontend application.
          pathType: Prefix
          serviceName: nginx-service   # The service that handles requests to the root path.
          servicePort: 80  # The port that the service exposes.

  # TLS configuration for secure HTTPS access
  tls: 
    - secretName: argocd-tls  # TLS secret used to store SSL certificates for securing the connection.
      hosts: 
        -  argocd.local # The hostname associated with the SSL certificate for HTTPS.