# Deployment Configuration

#annotations:
#  reloader.stakater.com/auto: "true" # Annotation for the Stakater Reloader, which automatically restarts the pod if ConfigMaps or Secrets change.

replicas: 2 # Defines the number of replicas for the deployment. In this case, two pods will be deployed.

#securityContextEnabled: true # Add securityContext flag
#securityContext: # Add default values for the securityContext
#   runAsUser: 65534  # nobody user
#   runAsGroup: 65534  # nogroup group

image:
  repository: nginx # Specifies the Docker image repository from an Azure Container Registry.
  tag: latest

container:
  name: nginx # Name of the container in the pod.
  port: 80 # Port on which the container will listen for incoming requests.

resources:
  limits:
    cpu: "500m"     # Maximum CPU allocation for the container (500 milliCPU).
    memory: "256Mi" # Maximum memory allocation for the container (256 MiB).
  requests:
    cpu: "200m"     # Minimum CPU allocation requested for the container (200 milliCPU).
    memory: "128Mi" # Minimum memory allocation requested for the container (128 MiB).



#
# ConfigMap Data
configMap:
  data:
    ASPNETCORE_ENVIRONMENT: "Development" # Environment variable for the .NET application, indicating the environment is "Development".
    


# Secret Data
secrets:
  data:
    AuditLogDbConnectionString: AgAWu+4oWgDPYid34LC0Ejmkqh03htgTFhzuAWVGby0fxFOCWmTeqOn3RzI95kkwCz2G/+R9OD5T/rlKj3iNJoQbMnEFhpZF5/OhJVcou7tWyC+zR2SjyTWjOjEOkjYWCtmqf9Yv74un5HilT82nBin2Ocj+RmhqnAEfHPqzg+kRL2tquEJPOZ7zH8Zy7XYds2XP6iDBsJrsIrd+xiTZKYofbsAToAh/VpgrpTRqxpGWaiks1VhjoXGsNMEdI9HE5EZJkhtndGK3Q0rHo7yFFoAO2IwH4O8GPOomkgoQwwdlITywW9Tr3vk2mnWH62DZksJYpyIYKhaFEm0KNgQK7Ee0qK2I0sUa0P1UizxXW3Z5w2fzKy1tTJ864JWbkMv58ukQvmJjVX+5e4B6kivA7IUclwxuNrAgAMdGtcIDYvKKekqo2nMMeDtCuexn8PQ2GcGyDg3yMVAe4pxLUmvi4OkwyCbn87x4D7NQ/sO2qEq8Ovwthtrl7oS5isTP3ZWTh1Aq4y6KwOHw+41/YvOQT/VRNtbCYtSo+7J3CgHIxc6fKYBtNaid7UZ1j4Mp+vopxU1/LOmSpSqdVB00f4lRjHfhilR/XdA0sgf+L6DN696bvFD18U9s964KkMrs5/gM90COfrtroM8yJKir7vK9wqJDccH/MM9GOZ41habKptGXJ/xTtLDrqO4XDf9tNx5BKYXAvrG0npLe6QrFXdAQZl+yQUnTkoVXFUS2BTQJ3yy+PsRJC149B3RZ31F35aym7B3IAMOxE0BL8X+lBiKn7xpdJsnu/wtu5HICiXFOvNOQodoPrGLWerMLWDt2UlU35pgytv89VMAAV7mw2EbV6rzxK4DaIkjh1HcwkYgKhGwoMD322KbNQ6qavmtiE2LOSB+m/zJQJ75klkBbnAztzK9BGXi/b68CZ3NrgOX0Mw==
    CordysUsername: AgBQWGoscSOUi+eC4DGlGpUF2wigdwEgszaKELAqk7HSUsNSKw9NijA0LryOaHR4XsFD9f7hWnBMbjUhnUajykoEarOGbO6hPn+zftcjnzXjN94N3Fu9a7f4dPgUlYnLxQ7dJ7XfnBjq9lRqnvntaoF03NNRsK7L03w5MoNlcdixg1LYCkJNjU/DdjZttfdm17vao63ch0NnADrGVtGohhP+uTlpRsJEZmMZsV4XKM18tisiQj4R7P8f9Qw+srgOGLpNW6RwQG2+eCqP39uYNe1gSDuGAeDM/jtBz1oZAw0B2g3QjrZ5gbH7kxkf6DTLaMISAU1Munek4TkcsXJusvH824xtwEL7SIIl2Mq4ssNLpmkEQ4vrOzTdf/ry7QewYwQ7bTM3hne5Nxtc5Su20M0a100dYM4J0WbcM+98eVVOT191D3aKiUPnGm7Q3NrhCv00DAnfnAi2x3/HJ6ceEIpqZM70RJHEra+NTHKsgOtoHoyPPLcoSob4G/Ni8M7QabuzAo3Tus/Zo9XJo6dq/FrRL8ri2SX18REN9G8YYzCjzo0s2immvWP5egQbFQ1Lt4f0eAFpM2tTN+4OF5/GwVuodzjAH4Jpucoc7jqbN1V+uHbk5IlKIp/v9bN8RHBSvqzMX0JeYeOWh7lXpwk0haxzITkINZVwlYWlooT3GNXJjXnqalu1sbhXWi+HDCqoiyNPjhbNtXFWtuKl1/CRDg==
    OracleDbConnectionString: AgDAN2LAr+5Ru6jqvo0yzz1Z27y9ZpupUR8CTVTwVQ78hrTbQToWVnL2PSSPY06i4bPhtIgeG9Wa9fSLFg1tCQu66AXpu4kSVCyfSSBnQOYMWu5jOfTRkKNWM3rSead/SfiLFigmO90dfsXf+/a33PnolKukcaqUI7VCSfYI+j+7X5wYCeKFQIa4VZYNTKYVTLGe2UCnVDbf2KcmAlQ2IIvymTcFp7/sg1ErR279MyCk5Behf3OLzGkyK3VdsQ05h/AKJNBCEY8DnZ6HDw1oQ2xWZHsV5KIEd+YF7HZUC08l65qSp7gfkvol5dwN0U/+iUCju1qUPbbEQYM5He+pTUusLbmlHjI3T/21JAeW+4ly21RerinGOEOrIEgkmr4ffzGUqFLItYAu+90GZt1JLtRwkBABST1wEV9mqj8aKTK9WUcSqmyv8IDrSkzCBz4UKE3TwAonZpy1d99Ql4YyUXz8W2KJueq3x0PAuDKNcCWTRe+c+Zj/dX17pIHF+pkeLotBhmzZfbC9yU3SouG8pV2rcS27HSSbFaaJFIIKvDTEdB5vcF8TD11s+o6ZC+Hops2me8gBa0pQEbwqL1NINNQNoNF1pn7oImObMvqn+i9odKF6HEWpKVPRgupFBUWktHJls3g4vDWPK87rzQ3krGzqRiEIJSoyNe5bDdDzkAvqezYTRc4JpXAHwaKhy/P+c3DIodSg7xqu5utjjLroxi+gpfY1ZASbdayFYR2j0ywREQZ2Dy43pa6Ee32bELY3FZkLdv4wchKCLWnPyuYHsbksXUMzR+Sv9aTx6w3ePxKFny/AwoJQ7J4YkvshNVEdge6FRNZOV1nRk215+tBeG9wzSG83W2LtcSkVbO+enfnDKwIpnFvWvIpS4KGn6AgRhjATXKIkklq1YbAvST9eikeqruFwP/Krpi4SOS7SOy/HXkaW46jga3duWmRwFg==
# Service Configuration
service:
  type: ClusterIP  # Defines the type of Kubernetes service. ClusterIP exposes the service internally within the cluster.
  port: 80         # Port that the service will expose externally (within the cluster in this case).
  targetPort: 80 # The port on the container to which the service will route traffic.

# Ingress Configuration
ingress:
  enabled: false # Enables the creation of an Ingress resource to manage external access to the service.
  className: "nginx"  # Specifies the Ingress class for the controller, in this case NGINX (e.g., it could be Traefik or another controller).

  # Ingress annotations (can be used to configure specific ingress controller features)
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"  # Example annotation for NGINX Ingress to rewrite URLs. Uncomment if needed.

  hosts:
    - host:   # The hostname for accessing the application via Ingress.
      paths:
        - path: /nginx(/|$)(.*)       # The root path for the frontend application.
          pathType: Prefix
          serviceName: nginx-service   # The service that handles requests to the root path.
          servicePort: 80  # The port that the service exposes.

  # TLS configuration for secure HTTPS access
  tls: 
    - secretName: argocd-tls  # TLS secret used to store SSL certificates for securing the connection.
      hosts: 
        -  argocd.local # The hostname associated with the SSL certificate for HTTPS.