apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Release.Name }}-app
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}