apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      {{- if .Values.securityContextEnabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      {{- end }}
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        env:
        {{- range $key, $value := .Values.configMap.data }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Release.Name }}-configmap
              key: {{ $key }}
        {{- end }}
        {{- range $key, $value := .Values.secrets.data }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-secret
              key: {{ $key }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      tolerations:
      {{- range .Values.tolerations }}
        - key: "{{ .key }}"
          operator: "{{ .operator }}"
          value: "{{ .value }}"
          effect: "{{ .effect }}"
      {{- end }}