# templates/sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}-app
  annotations:
    # Ensures the secret can only be unsealed in the target namespace
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Release.Name }}-secret
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Release.Name }}-app
    type: Opaque