apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}-app
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Release.Name }}-secret
      labels:
        app: {{ .Release.Name }}-app
    type: Opaque
